CREATE TABLE imagem (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    idObjeto INT NOT NULL,
    nomeArquivo VARCHAR(255) DEFAULT NULL,
    pasta VARCHAR(255) DEFAULT NULL,
    imagem VARCHAR(255) DEFAULT NULL
)  ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;