CREATE TABLE mensagem (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    conteudo varchar(255) DEFAULT NULL,
    datahora DATETIME DEFAULT CURRENT_TIMESTAMP
)  ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE ordem_servico (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    idTrabalhador INT NOT NULL DEFAULT 0,
    idSolicitante INT NOT NULL DEFAULT 0,
    virouServico TINYINT NOT NULL DEFAULT 0,
    valor DECIMAL(10,2) DEFAULT 0.0,
    status TINYINT NOT NULL DEFAULT 0,
    ativo TINYINT NOT NULL DEFAULT 1,
    dataCriacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)  ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;